myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"#name of the urlspace
#name of the url space is not mandatory
#if it is not given navigation jinja tag will be {% url 'mappingname' %}
urlpatterns = [
    path('sample2/<data>',views.sample2,name="sample2"),
    path('sample3/',views.sample3,name="sample3")
    
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
    path('sample1/',views.sample1,name="sample1"),

]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render

# Create your views here.
def sample1(request):
    return render(request,"sample1.html")

def sample2(request,data):
    return render(request,"myapp/sample2.html",context={'data':data})

def sample3(request):
    return render(request,"myapp/sample3.html",context={'name':"akshay"})

templates/myapp/sample2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample2</title>
</head>
<body>
    <h1>Welcome to sample2.html Page</h1>
    <h2>I am Carrying the data in the URL and the data is {{data}}</h3>
    <a href="{% url 'sample1' %}">Sample1</a><br>
    <a href="{% url 'myapp:sample3' %}">Sample3</a>
    </body>
</html>

templates/myapp/sample3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample3</title>
</head>
<body>
    <h1>Welcome to sample3</h1>
    <h2>Data Carried from Backend {{name}}</h2>
    <a href="{% url 'sample1' %}">Sample1</a>
    <br><a href="{% url 'myapp:sample2' data=name %}">Sample2</a>
</body>
</html>

templates/sample1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample1</title>
</head>
<body>
    <h1>Welcome to sample.html Page</h1>
    <a href="{% url 'myapp:sample2' data='Hello World' %}">Sample2</a>
    <br><a href="{% url 'myapp:sample3' %}">Sample3</a>
</body>
</html>